spring:
  application:
     name: inventory_api
  datasource:
    url: jdbc:mysql://localhost:3306/inventory?createDatabaseIfNotExist=true
    username: root
    password: 12345
  jpa:
    hibernate:
      show-sql: true